name: Deploy POS to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute commands on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /var/www/pos

            echo "===== Reset Repository ====="
            git pull origin main
            
            echo "===== Install Composer Packages ====="
            composer install --no-dev --no-interaction --prefer-dist

            echo "===== Generate Autoload ====="
            composer dump-autoload
            php artisan optimize:clear

            echo "===== Install Node Packages ====="
            npm ci

            echo "===== Build Assets ====="
            npm run build

            echo "===== Laravel ====="
            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            php artisan queue:restart

            echo "===== Reload Services ====="
            systemctl reload php8.3-fpm
            systemctl reload nginx