name: Deploy POS to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute commands on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /var/www/pos

            echo "===== Current Directory ====="
            pwd

            echo "===== Current User ====="
            whoami

            echo "===== Reset Repository ====="
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "===== Composer Install ====="
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            echo "===== Composer Autoload ====="
            composer dump-autoload

            echo "===== Node Build ====="
            npm ci
            npm run build

            echo "===== Laravel ====="
            php artisan optimize:clear
            php artisan migrate --force

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            php artisan queue:restart

            echo "===== Restart Services ====="
            systemctl reload php8.3-fpm
            systemctl reload nginx

            echo "===== Deployment Complete ====="